### ISSUE TITLE
ssr and ssg

### ISSUE THREAD

**Issue by badgeek** [ijjk/notion-blog#13]
what is the difference between this repo and the spr landing version, it seems the spr already renamed to ssg? thanks

**Comment by ijjk** [comment]
Hi, the spr-landing repo was the initial demo which demonstrated our initial implementation of serverless pre-rendering. It has since been updated with the same code from this repo in case anyone is looking there they see the latest implementation. 

SSG in Next.js is the evolved version of the SPR feature which handles more cases like pre-populating a deployment's cache during the build to ensure a page is always available and allowing the data request for a page on a separate URL be linked to the page itself so the two are in sync. More details will be released on this after these APIs are made stable in Next.js. Stay tuned!
