### ISSUE TITLE
Blog posts don't show

### ISSUE THREAD

**Issue by plooliveira** [ijjk/notion-blog#15]
I followed all the steps, set the token and ID, but the posts do not appear. what could it be?

**Comment by ijjk** [comment]
Without any additional information like logs, a repo that it's occurring with, or a deployment link it's hard to say. One possible reason could be you have an invalid table set-up on the provided page in Notion and it's not able to fetch the posts.

If you start with a blank page in Notion and provide the id the first time you build the`notion-blog` it will create the table on the provided page for you.

I'm gonna close this since it isn't really actionable, but feel free to reply with additional details if you are still having trouble

**Comment by plooliveira** [comment]
Thanks, It was a table issue.
