### ISSUE TITLE
Other Language Support for Syntax Highlight

### ISSUE THREAD

**Issue by toshimaru** [ijjk/notion-blog#2]
When I used a language like Ruby, the following error occurred.

```
ERROR	TypeError: Cannot read property 'rest' of undefined
```

This is because Prism doesn't support languages like Ruby by default.

https://github.com/ijjk/notion-blog/blob/3acc5bdd8e4d219a0455be4f0202f81f7f1820fe/src/components/code.tsx#L9-L12

**Comment by ijjk** [comment]
Hi, support for other languages can be added by importing the language component in the [code component](https://github.com/ijjk/notion-blog/blob/master/src/components/code.tsx#L2). For ruby this would be `import 'prismjs/components/prism-ruby'`.

I updated this component to gracefully handle the language not being loaded instead of showing the above error.
