### ISSUE TITLE
[suggestion]: add pagination to blog index page

### ISSUE THREAD

**Issue by dongsuo** [ijjk/notion-blog#20]
I notice that there is a comment in ```getBlogIndex.ts```: 
`// only get 10 most recent post's previews`
I dont't know why only 10, but I guess too much preview may effect performance, so I suggest maybe pagination is a good way to solve this.

**Comment by ijjk** [comment]
This is because the content is prerendered and it's a tradeoff between fetching more preview data with the cost of longer build times or limiting the number of previews and having more reasonable build times. 

Pagination wouldn't solve this specific case and currently is above the scope of the example so I'm going to close this for now but thanks for the recommendation!
