### ISSUE TITLE
Support running on local via docker

### ISSUE THREAD

**Issue by ardinusawan** [ijjk/notion-blog#37]
Need help to make it 🙏🙏

**Comment by ijjk** [comment]
Hi, you should be able to configure this project to run inside of docker like any other Next.js application although you won't have as streamlined of an experience as you would deploying it on [Vercel](https://github.com/ijjk/notion-blog#deploy-your-own). 

If you are having trouble with a specific part of this I could provide additional help but without more information it can be hard to tell what part you need help on. I'm gonna close this since it isn't an issue with the project although feel free to reply with additional info about what you are looking for help with on this.
